### ISSUE TITLE
When date time is set with BC date, all time units but year go backwards

### ISSUE THREAD

**Issue by homedry** [ivoyager/ivoyager#10]
**I, Voyager platform**

Planetarium using web browser

**I, Voyager version and (if applicable) Godot version**
v0.0.13

**OS/device**
Ubuntu 22.04.1 LTS

**Issue description:**
If the time direction is normal, when date is BC date, all the date time units should shrink to 0001/01/01 00:00:00 BC(YYYY/MM/DD HH:MM:SS).
But all the units but year increase.
(Maybe BC date was not considered. If so, please consider the function)

**Steps to reproduce**
1. Set year of date time negative enough.
2. Keep time direction normal.

**Minimal project**

**[Optional] Other helpful information**

**Comment by charliewhitfield** [comment]
That's interesting! Shouldn't take me to long to figure this out and fix.

**Comment by charliewhitfield** [comment]
I haven't been able to replicate this. When I set year to -2023, the years get less negative as month and day go up (or the reverse if I press the '<' reverse button).

I just uploaded the new [v0.0.14 Planetarium](https://www.ivoyager.dev/planetarium/). Please give it a try and re-open this issue if you're still seeing the problem.
