### ISSUE TITLE
LunCo: full-cycle space operations sim tool

### ISSUE THREAD

**Issue by 0xIonRod** [ivoyager/ivoyager#9]
Hi!
I'm working on https://github.com/LunCoSim/lunco-sim

You project is amazing!

I'd like to reuse it in my project.

It would be amazing if we could get in touch

**Comment by charliewhitfield** [comment]
Hi Difint, You can absolutely use I, Voyager. Come on over to our discussion forum (you can find a link around here somewhere). I’m trying to keep issues for bugs only. I’ll take a look at your project when I’m back from vacation in a week.

**Comment by 0xIonRod** [comment]
Amazing!

I also followed you in Twitter, please follow back and open DM just in case

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by charliewhitfield** [comment]
Closing since this isn't an issue.

Do come try our new [v0.0.14 Planetarium](https://www.ivoyager.dev/planetarium/) that I just uploaded!
